#!/usr/bin/env bash
# =============================================================================
# ACBU Contract-Address Registry Update Script
# W2-C-062: guarded deploy pipeline with contract-address registry
#
# Usage (called by deploy.sh automatically):
#   ./scripts/update_registry.sh <network> <network_json_path>
#
# Usage (manual refresh after a one-off deploy):
#   ./scripts/update_registry.sh testnet deployments/testnet.json
#
# The registry (deployments/registry.json) is a canonical, git-tracked file
# that records every contract address for every deployed network.  It is
# safe to commit — no secrets are stored here.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_DIR="$PROJECT_ROOT/deployments"
REGISTRY="$DEPLOY_DIR/registry.json"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[registry]${NC} $*"; }
warn()  { echo -e "${YELLOW}[registry]${NC} $*"; }
error() { echo -e "${RED}[registry] ERROR:${NC} $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------
NETWORK="${1:-}"
NETWORK_FILE="${2:-}"

if [[ -z "$NETWORK" || -z "$NETWORK_FILE" ]]; then
    error "Usage: $0 <network> <network_json_path>"
fi

if [[ ! -f "$NETWORK_FILE" ]]; then
    error "Network deployment file not found: ${NETWORK_FILE}"
fi

mkdir -p "$DEPLOY_DIR"

# ---------------------------------------------------------------------------
# Build or update registry.json
# We use Python (available in GitHub Actions ubuntu-latest) for JSON merge.
# Falls back to a pure-bash approach if python3 is missing.
# ---------------------------------------------------------------------------
if command -v python3 &>/dev/null; then
    python3 - "$NETWORK" "$NETWORK_FILE" "$REGISTRY" <<'PYEOF'
import json, sys, os

network      = sys.argv[1]
network_file = sys.argv[2]
registry_path = sys.argv[3]

# Load network snapshot
with open(network_file) as f:
    snapshot = json.load(f)

# Load or init registry
if os.path.exists(registry_path):
    with open(registry_path) as f:
        registry = json.load(f)
else:
    registry = {
        "_comment": "Auto-generated by scripts/update_registry.sh — do not edit by hand.",
        "_schema": "1",
        "networks": {}
    }

# Upsert this network's entry
registry["networks"][network] = {
    "deployed_at":        snapshot.get("deployed_at", ""),
    "git_sha":            snapshot.get("git_sha", ""),
    "git_ref":            snapshot.get("git_ref", ""),
    "network_passphrase": snapshot.get("network_passphrase", ""),
    "rpc_url":            snapshot.get("rpc_url", ""),
    "contracts":          snapshot.get("contracts", {})
}

with open(registry_path, "w") as f:
    json.dump(registry, f, indent=2)
    f.write("\n")

print(f"Registry updated for network '{network}'.")
PYEOF

else
    # Fallback: write a minimal registry containing only the latest network
    warn "python3 not found — writing minimal registry (only ${NETWORK})."
    jq --argjson snap "$(cat "$NETWORK_FILE")" \
        --arg net "$NETWORK" \
        '.networks[$net] = {
            deployed_at: $snap.deployed_at,
            git_sha: $snap.git_sha,
            git_ref: $snap.git_ref,
            network_passphrase: $snap.network_passphrase,
            rpc_url: $snap.rpc_url,
            contracts: $snap.contracts
        }' \
        "${REGISTRY:-/dev/null}" 2>/dev/null \
    || python3 -c "
import json
snap = json.load(open('$NETWORK_FILE'))
reg = {'_comment': 'Auto-generated by scripts/update_registry.sh', '_schema': '1', 'networks': {'$NETWORK': snap}}
json.dump(reg, open('$REGISTRY', 'w'), indent=2)
print('Registry written.')
"
fi

# ---------------------------------------------------------------------------
# Show current registry state
# ---------------------------------------------------------------------------
info "Registry: ${REGISTRY}"
if command -v python3 &>/dev/null; then
    python3 - "$REGISTRY" <<'PYEOF'
import json, sys
with open(sys.argv[1]) as f:
    reg = json.load(f)
print("")
for net, data in reg.get("networks", {}).items():
    print(f"  [{net}]  deployed_at={data.get('deployed_at','?')}  git_sha={data.get('git_sha','?')[:8]}")
    for k, v in data.get("contracts", {}).items():
        print(f"    {k:<20} {v}")
    print("")
PYEOF
fi
